#!/bin/bash
# OpenVPN 安装脚本 - 配置管理库
# OpenVPN Install - Configuration Management Library
# 配置文件管理和持久化
# Configuration file management and persistence

# =============================================================================
# 配置文件路径 / Configuration File Paths
# =============================================================================

# OpenVPN 服务器配置目录
# OpenVPN server configuration directory
readonly OPENVPN_CONFIG_DIR="/etc/openvpn/server"

# 配置文件路径
# Configuration file path
readonly CONFIG_FILE="${OPENVPN_CONFIG_DIR}/openvpn-install.conf"

# =============================================================================
# 配置初始化 / Configuration Initialization
# =============================================================================

# 初始化配置系统
# Initialize configuration system
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
config_init() {
	log_debug "初始化配置系统 / Initializing configuration system"
	
	# 确保配置目录存在 / Ensure config directory exists
	if [[ ! -d "$OPENVPN_CONFIG_DIR" ]]; then
		mkdir -p "$OPENVPN_CONFIG_DIR" || {
			log_error "无法创建配置目录 / Failed to create config directory: $OPENVPN_CONFIG_DIR"
			return 1
		}
	fi
	
	# 创建空配置文件（如果不存在）
	# Create empty config file if it doesn't exist
	if [[ ! -f "$CONFIG_FILE" ]]; then
		cat > "$CONFIG_FILE" <<-EOF
		# OpenVPN 安装配置 / OpenVPN Installation Configuration
		# 此文件由 openvpn-install.sh 自动生成
		# This file is automatically generated by openvpn-install.sh
		# 创建时间 / Created: $(date '+%Y-%m-%d %H:%M:%S')
		EOF
		
		chmod 600 "$CONFIG_FILE"
		log_success "配置文件已创建 / Configuration file created: $CONFIG_FILE"
	fi
	
	return 0
}

# =============================================================================
# 配置读写操作 / Configuration Read/Write Operations
# =============================================================================

# 设置配置值
# Set configuration value
# 参数 / Args:
#   $1 - 配置键名 / configuration key
#   $2 - 配置值 / configuration value
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
config_set() {
	local key="$1"
	local value="$2"
	
	if [[ -z "$key" ]]; then
		log_error "配置键名不能为空 / Configuration key cannot be empty"
		return 1
	fi
	
	log_debug "设置配置 / Setting config: $key = $value"
	
	# 初始化配置系统（如果需要）
	# Initialize config system if needed
	config_init || return 1
	
	# 移除旧值（如果存在）/ Remove old value if exists
	sed -i "/^${key}=/d" "$CONFIG_FILE" 2>/dev/null
	
	# 添加新值 / Add new value
	echo "${key}=${value}" >> "$CONFIG_FILE"
	
	return 0
}

# 获取配置值
# Get configuration value
# 参数 / Args:
#   $1 - 配置键名 / configuration key
#   $2 - 默认值（可选）/ default value (optional)
# 返回 / Returns: 配置值输出到 stdout / configuration value on stdout
config_get() {
	local key="$1"
	local default="${2:-}"
	
	if [[ -z "$key" ]]; then
		log_error "配置键名不能为空 / Configuration key cannot be empty"
		return 1
	fi
	
	# 检查配置文件是否存在 / Check if config file exists
	if [[ ! -f "$CONFIG_FILE" ]]; then
		echo "$default"
		return 0
	fi
	
	# 读取配置值 / Read configuration value
	local value
	value=$(grep "^${key}=" "$CONFIG_FILE" 2>/dev/null | cut -d= -f2-)
	
	if [[ -n "$value" ]]; then
		echo "$value"
	else
		echo "$default"
	fi
	
	return 0
}

# 删除配置值
# Delete configuration value
# 参数 / Args:
#   $1 - 配置键名 / configuration key
# 返回 / Returns: 成功返回 0 / 0 on success
config_delete() {
	local key="$1"
	
	if [[ -z "$key" ]]; then
		log_error "配置键名不能为空 / Configuration key cannot be empty"
		return 1
	fi
	
	log_debug "删除配置 / Deleting config: $key"
	
	if [[ -f "$CONFIG_FILE" ]]; then
		sed -i "/^${key}=/d" "$CONFIG_FILE"
	fi
	
	return 0
}

# =============================================================================
# 配置验证 / Configuration Validation
# =============================================================================

# 验证配置完整性
# Validate configuration integrity
# 返回 / Returns: 配置有效返回 0，无效返回 1 / 0 if valid, 1 if invalid
config_validate() {
	log_debug "验证配置完整性 / Validating configuration integrity"
	
	if [[ ! -f "$CONFIG_FILE" ]]; then
		log_warn "配置文件不存在 / Configuration file does not exist"
		return 1
	fi
	
	# 检查文件权限 / Check file permissions
	local perms
	perms=$(stat -c "%a" "$CONFIG_FILE" 2>/dev/null || stat -f "%Lp" "$CONFIG_FILE" 2>/dev/null)
	
	if [[ "$perms" != "600" ]]; then
		log_warn "配置文件权限不正确 / Configuration file has incorrect permissions: $perms (应为 / should be 600)"
		chmod 600 "$CONFIG_FILE"
		log_success "已修正权限 / Permissions corrected"
	fi
	
	return 0
}

# =============================================================================
# 配置导出和导入 / Configuration Export and Import
# =============================================================================

# 导出配置到文件
# Export configuration to file
# 参数 / Args:
#   $1 - 导出文件路径 / export file path
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
config_export() {
	local export_file="$1"
	
	if [[ -z "$export_file" ]]; then
		log_error "必须指定导出文件路径 / Export file path must be specified"
		return 1
	fi
	
	if [[ ! -f "$CONFIG_FILE" ]]; then
		log_error "配置文件不存在 / Configuration file does not exist"
		return 1
	fi
	
	log_info "导出配置到 / Exporting configuration to: $export_file"
	
	cp "$CONFIG_FILE" "$export_file" || {
		log_error "配置导出失败 / Configuration export failed"
		return 1
	}
	
	chmod 600 "$export_file"
	log_success "配置导出成功 / Configuration exported successfully"
	
	return 0
}

# 从文件导入配置
# Import configuration from file
# 参数 / Args:
#   $1 - 导入文件路径 / import file path
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
config_import() {
	local import_file="$1"
	
	if [[ -z "$import_file" ]]; then
		log_error "必须指定导入文件路径 / Import file path must be specified"
		return 1
	fi
	
	if [[ ! -f "$import_file" ]]; then
		log_error "导入文件不存在 / Import file does not exist: $import_file"
		return 1
	fi
	
	log_info "从文件导入配置 / Importing configuration from: $import_file"
	
	# 备份当前配置 / Backup current configuration
	if [[ -f "$CONFIG_FILE" ]]; then
		cp "$CONFIG_FILE" "${CONFIG_FILE}.backup" || {
			log_warn "无法备份当前配置 / Failed to backup current configuration"
		}
	fi
	
	# 导入新配置 / Import new configuration
	config_init || return 1
	cp "$import_file" "$CONFIG_FILE" || {
		log_error "配置导入失败 / Configuration import failed"
		# 恢复备份 / Restore backup
		if [[ -f "${CONFIG_FILE}.backup" ]]; then
			mv "${CONFIG_FILE}.backup" "$CONFIG_FILE"
		fi
		return 1
	fi
	
	chmod 600 "$CONFIG_FILE"
	log_success "配置导入成功 / Configuration imported successfully"
	
	# 验证导入的配置 / Validate imported configuration
	if ! config_validate; then
		log_warn "导入的配置可能无效 / Imported configuration may be invalid"
	fi
	
	return 0
}

# =============================================================================
# 配置显示 / Configuration Display
# =============================================================================

# 显示所有配置
# Display all configuration
# 返回 / Returns: 成功返回 0 / 0 on success
config_show() {
	if [[ ! -f "$CONFIG_FILE" ]]; then
		log_warn "配置文件不存在 / Configuration file does not exist"
		return 1
	fi
	
	log_header "当前配置 / Current Configuration"
	
	# 显示配置内容（排除注释）
	# Display configuration content (excluding comments)
	grep -v "^#" "$CONFIG_FILE" | grep -v "^$" | while IFS= read -r line; do
		echo "  $line"
	done
	
	return 0
}

# =============================================================================
# 便捷配置函数 / Convenience Configuration Functions
# =============================================================================

# 保存服务器名称
# Save server name
# 参数 / Args: $1 - 服务器名称 / server name
config_set_server_name() {
	config_set "SERVER_NAME" "$1"
}

# 获取服务器名称
# Get server name
config_get_server_name() {
	config_get "SERVER_NAME" "server"
}

# 保存认证模式
# Save authentication mode
# 参数 / Args: $1 - 认证模式 (pki 或 fingerprint) / auth mode (pki or fingerprint)
config_set_auth_mode() {
	config_set "AUTH_MODE" "$1"
}

# 获取认证模式
# Get authentication mode
config_get_auth_mode() {
	config_get "AUTH_MODE" "pki"
}

# 保存端口号
# Save port number
# 参数 / Args: $1 - 端口号 / port number
config_set_port() {
	config_set "PORT" "$1"
}

# 获取端口号
# Get port number
config_get_port() {
	config_get "PORT" "1194"
}

# 保存协议
# Save protocol
# 参数 / Args: $1 - 协议 (udp 或 tcp) / protocol (udp or tcp)
config_set_protocol() {
	config_set "PROTOCOL" "$1"
}

# 获取协议
# Get protocol
config_get_protocol() {
	config_get "PROTOCOL" "udp"
}
