#!/bin/bash
# OpenVPN 安装脚本 - 防火墙管理库
# OpenVPN Install - Firewall Management Library
# 防火墙规则管理（firewalld、nftables、iptables）
# Firewall rules management (firewalld, nftables, iptables)

# =============================================================================
# 防火墙检测 / Firewall Detection
# =============================================================================

# 检测系统使用的防火墙类型
# Detect which firewall system is in use
# 返回 / Returns: 防火墙类型输出到 stdout / firewall type on stdout
#                 (firewalld, nftables, iptables, 或 none)
firewall_detect() {
	log_debug "检测防火墙系统 / Detecting firewall system"
	
	# 检查 firewalld / Check for firewalld
	if systemctl is-active --quiet firewalld 2>/dev/null; then
		echo "firewalld"
		log_debug "检测到 firewalld / Detected firewalld"
		return 0
	fi
	
	# 检查 nftables / Check for nftables
	if command -v nft >/dev/null 2>&1 && nft list tables 2>/dev/null | grep -q .; then
		echo "nftables"
		log_debug "检测到 nftables / Detected nftables"
		return 0
	fi
	
	# 检查 iptables / Check for iptables
	if command -v iptables >/dev/null 2>&1; then
		echo "iptables"
		log_debug "检测到 iptables / Detected iptables"
		return 0
	fi
	
	# 未检测到防火墙 / No firewall detected
	echo "none"
	log_warn "未检测到防火墙系统 / No firewall system detected"
	return 0
}

# =============================================================================
# IP 转发配置 / IP Forwarding Configuration
# =============================================================================

# 启用 IP 转发
# Enable IP forwarding
# 参数 / Args:
#   $1 - IP 版本 (4 或 6 或 both) / IP version (4 or 6 or both)
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
firewall_enable_forwarding() {
	local ip_version="${1:-both}"
	
	log_info "启用 IP 转发 / Enabling IP forwarding: IPv$ip_version"
	
	local sysctl_file="/etc/sysctl.d/99-openvpn.conf"
	
	# 创建 sysctl 配置文件 / Create sysctl config file
	cat > "$sysctl_file" <<-EOF
	# OpenVPN IP 转发配置 / OpenVPN IP Forwarding Configuration
	# 由 openvpn-install.sh 自动生成 / Automatically generated by openvpn-install.sh
	EOF
	
	case "$ip_version" in
		4)
			echo "net.ipv4.ip_forward = 1" >> "$sysctl_file"
			sysctl -w net.ipv4.ip_forward=1 >/dev/null
			;;
		6)
			echo "net.ipv6.conf.all.forwarding = 1" >> "$sysctl_file"
			sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null
			;;
		both|*)
			{
				echo "net.ipv4.ip_forward = 1"
				echo "net.ipv6.conf.all.forwarding = 1"
			} >> "$sysctl_file"
			sysctl -w net.ipv4.ip_forward=1 >/dev/null
			sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null
			;;
	esac
	
	log_success "IP 转发已启用 / IP forwarding enabled"
	return 0
}

# =============================================================================
# firewalld 规则管理 / firewalld Rules Management
# =============================================================================

# 添加 firewalld 规则
# Add firewalld rules
# 参数 / Args:
#   $1 - 端口号 / port number
#   $2 - 协议 / protocol (udp or tcp)
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
firewall_add_firewalld() {
	local port="$1"
	local protocol="$2"
	
	log_info "添加 firewalld 规则 / Adding firewalld rules: port $port/$protocol"
	
	# 添加端口规则 / Add port rule
	if ! firewall-cmd --permanent --add-port="${port}/${protocol}" >/dev/null 2>&1; then
		log_error "无法添加防火墙端口规则 / Failed to add firewall port rule"
		return 1
	fi
	
	# 添加伪装（NAT）/ Add masquerade (NAT)
	if ! firewall-cmd --permanent --add-masquerade >/dev/null 2>&1; then
		log_warn "无法添加伪装规则 / Failed to add masquerade rule"
	fi
	
	# 重新加载防火墙 / Reload firewall
	if ! firewall-cmd --reload >/dev/null 2>&1; then
		log_error "无法重新加载防火墙 / Failed to reload firewall"
		return 1
	fi
	
	log_success "firewalld 规则添加成功 / firewalld rules added successfully"
	return 0
}

# 移除 firewalld 规则
# Remove firewalld rules
# 参数 / Args:
#   $1 - 端口号 / port number
#   $2 - 协议 / protocol (udp or tcp)
# 返回 / Returns: 成功返回 0 / 0 on success
firewall_remove_firewalld() {
	local port="$1"
	local protocol="$2"
	
	log_info "移除 firewalld 规则 / Removing firewalld rules: port $port/$protocol"
	
	firewall-cmd --permanent --remove-port="${port}/${protocol}" >/dev/null 2>&1
	firewall-cmd --permanent --remove-masquerade >/dev/null 2>&1
	firewall-cmd --reload >/dev/null 2>&1
	
	log_success "firewalld 规则已移除 / firewalld rules removed"
	return 0
}

# =============================================================================
# iptables 规则管理 / iptables Rules Management
# =============================================================================

# 添加 iptables 规则
# Add iptables rules
# 参数 / Args:
#   $1 - 端口号 / port number
#   $2 - 协议 / protocol (udp or tcp)
#   $3 - VPN 子网 / VPN subnet (e.g., 10.8.0.0/24)
#   $4 - 网络接口 / network interface
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
firewall_add_iptables() {
	local port="$1"
	local protocol="$2"
	local vpn_subnet="$3"
	local interface="$4"
	
	log_info "添加 iptables 规则 / Adding iptables rules"
	
	local iptables_dir="/etc/iptables"
	local add_rules="${iptables_dir}/add-openvpn-rules.sh"
	local rm_rules="${iptables_dir}/rm-openvpn-rules.sh"
	
	# 创建 iptables 目录 / Create iptables directory
	mkdir -p "$iptables_dir"
	
	# 创建添加规则脚本 / Create add rules script
	cat > "$add_rules" <<-EOF
	#!/bin/bash
	# OpenVPN iptables 规则 / OpenVPN iptables rules
	# 添加规则 / Add rules
	
	# 允许 OpenVPN 端口 / Allow OpenVPN port
	iptables -I INPUT -p ${protocol} --dport ${port} -j ACCEPT
	
	# 允许来自 VPN 的流量 / Allow traffic from VPN
	iptables -I INPUT -i tun0 -j ACCEPT
	iptables -I FORWARD -i tun0 -j ACCEPT
	iptables -I FORWARD -o tun0 -j ACCEPT
	
	# NAT 规则 / NAT rules
	iptables -t nat -I POSTROUTING -s ${vpn_subnet} -o ${interface} -j MASQUERADE
	EOF
	
	chmod +x "$add_rules"
	
	# 创建移除规则脚本 / Create remove rules script
	cat > "$rm_rules" <<-EOF
	#!/bin/bash
	# OpenVPN iptables 规则清理 / OpenVPN iptables rules cleanup
	# 移除规则 / Remove rules
	
	iptables -D INPUT -p ${protocol} --dport ${port} -j ACCEPT 2>/dev/null
	iptables -D INPUT -i tun0 -j ACCEPT 2>/dev/null
	iptables -D FORWARD -i tun0 -j ACCEPT 2>/dev/null
	iptables -D FORWARD -o tun0 -j ACCEPT 2>/dev/null
	iptables -t nat -D POSTROUTING -s ${vpn_subnet} -o ${interface} -j MASQUERADE 2>/dev/null
	EOF
	
	chmod +x "$rm_rules"
	
	# 执行添加规则脚本 / Execute add rules script
	if ! bash "$add_rules"; then
		log_error "无法应用 iptables 规则 / Failed to apply iptables rules"
		return 1
	fi
	
	# 创建 systemd 服务以在启动时应用规则
	# Create systemd service to apply rules on boot
	cat > /etc/systemd/system/iptables-openvpn.service <<-EOF
	[Unit]
	Description=iptables rules for OpenVPN
	Before=network-pre.target
	Wants=network-pre.target
	
	[Service]
	Type=oneshot
	ExecStart=${add_rules}
	ExecStop=${rm_rules}
	RemainAfterExit=yes
	
	[Install]
	WantedBy=multi-user.target
	EOF
	
	systemctl daemon-reload
	systemctl enable iptables-openvpn.service >/dev/null 2>&1
	
	log_success "iptables 规则添加成功 / iptables rules added successfully"
	return 0
}

# 移除 iptables 规则
# Remove iptables rules
# 返回 / Returns: 成功返回 0 / 0 on success
firewall_remove_iptables() {
	log_info "移除 iptables 规则 / Removing iptables rules"
	
	local rm_rules="/etc/iptables/rm-openvpn-rules.sh"
	
	# 执行移除规则脚本 / Execute remove rules script
	if [[ -f "$rm_rules" ]]; then
		bash "$rm_rules" 2>/dev/null
	fi
	
	# 停用并删除 systemd 服务 / Disable and remove systemd service
	systemctl disable iptables-openvpn.service >/dev/null 2>&1
	rm -f /etc/systemd/system/iptables-openvpn.service
	systemctl daemon-reload
	
	# 删除脚本文件 / Remove script files
	rm -f /etc/iptables/add-openvpn-rules.sh
	rm -f /etc/iptables/rm-openvpn-rules.sh
	
	log_success "iptables 规则已移除 / iptables rules removed"
	return 0
}

# =============================================================================
# nftables 规则管理 / nftables Rules Management
# =============================================================================

# 添加 nftables 规则
# Add nftables rules
# 参数 / Args:
#   $1 - 端口号 / port number
#   $2 - 协议 / protocol (udp or tcp)
#   $3 - VPN 子网 / VPN subnet
#   $4 - 网络接口 / network interface
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
firewall_add_nftables() {
	local port="$1"
	local protocol="$2"
	local vpn_subnet="$3"
	local interface="$4"
	
	log_info "添加 nftables 规则 / Adding nftables rules"
	
	# 创建 nftables 配置 / Create nftables configuration
	local nft_conf="/etc/nftables.d/openvpn.nft"
	mkdir -p /etc/nftables.d
	
	cat > "$nft_conf" <<-EOF
	# OpenVPN nftables 规则 / OpenVPN nftables rules
	
	table ip openvpn {
		chain input {
			type filter hook input priority 0; policy accept;
			${protocol} dport ${port} accept
			iifname "tun0" accept
		}
		
		chain forward {
			type filter hook forward priority 0; policy accept;
			iifname "tun0" accept
			oifname "tun0" accept
		}
		
		chain postrouting {
			type nat hook postrouting priority 100;
			ip saddr ${vpn_subnet} oifname "${interface}" masquerade
		}
	}
	EOF
	
	# 加载 nftables 规则 / Load nftables rules
	if ! nft -f "$nft_conf"; then
		log_error "无法加载 nftables 规则 / Failed to load nftables rules"
		return 1
	fi
	
	log_success "nftables 规则添加成功 / nftables rules added successfully"
	return 0
}

# 移除 nftables 规则
# Remove nftables rules
# 返回 / Returns: 成功返回 0 / 0 on success
firewall_remove_nftables() {
	log_info "移除 nftables 规则 / Removing nftables rules"
	
	# 删除表 / Delete table
	nft delete table ip openvpn 2>/dev/null
	
	# 删除配置文件 / Remove config file
	rm -f /etc/nftables.d/openvpn.nft
	
	log_success "nftables 规则已移除 / nftables rules removed"
	return 0
}

# =============================================================================
# 统一防火墙接口 / Unified Firewall Interface
# =============================================================================

# 添加防火墙规则（自动检测防火墙类型）
# Add firewall rules (auto-detect firewall type)
# 参数 / Args:
#   $1 - 端口号 / port number
#   $2 - 协议 / protocol (udp or tcp)
#   $3 - VPN 子网 / VPN subnet (可选，iptables/nftables 需要)
#   $4 - 网络接口 / network interface (可选，iptables/nftables 需要)
# 返回 / Returns: 成功返回 0，失败返回 1 / 0 on success, 1 on failure
firewall_add_rules() {
	local port="$1"
	local protocol="$2"
	local vpn_subnet="${3:-10.8.0.0/24}"
	local interface="${4:-$(get_default_interface)}"
	
	local fw_type
	fw_type=$(firewall_detect)
	
	log_info "使用 $fw_type 添加防火墙规则 / Adding firewall rules using $fw_type"
	
	case "$fw_type" in
		firewalld)
			firewall_add_firewalld "$port" "$protocol"
			;;
		nftables)
			firewall_add_nftables "$port" "$protocol" "$vpn_subnet" "$interface"
			;;
		iptables)
			firewall_add_iptables "$port" "$protocol" "$vpn_subnet" "$interface"
			;;
		none)
			log_warn "未检测到防火墙，跳过规则添加 / No firewall detected, skipping rule addition"
			return 0
			;;
		*)
			log_error "未知的防火墙类型 / Unknown firewall type: $fw_type"
			return 1
			;;
	esac
}

# 移除防火墙规则（自动检测防火墙类型）
# Remove firewall rules (auto-detect firewall type)
# 参数 / Args:
#   $1 - 端口号 / port number (可选) / optional
#   $2 - 协议 / protocol (可选) / optional
# 返回 / Returns: 成功返回 0 / 0 on success
firewall_remove_rules() {
	local port="${1:-}"
	local protocol="${2:-}"
	
	local fw_type
	fw_type=$(firewall_detect)
	
	log_info "使用 $fw_type 移除防火墙规则 / Removing firewall rules using $fw_type"
	
	case "$fw_type" in
		firewalld)
			if [[ -n "$port" && -n "$protocol" ]]; then
				firewall_remove_firewalld "$port" "$protocol"
			fi
			;;
		nftables)
			firewall_remove_nftables
			;;
		iptables)
			firewall_remove_iptables
			;;
		none)
			log_info "未检测到防火墙，无需移除规则 / No firewall detected, nothing to remove"
			return 0
			;;
		*)
			log_warn "未知的防火墙类型 / Unknown firewall type: $fw_type"
			return 0
			;;
	esac
}
